/**
 * MSW handlers for the three explorer operations of `api/openapi.yaml`:
 * the settlements listing, the records listing, and the per-match detail the
 * settlement breakdown opens.
 *
 * Kept out of `handlers.ts` so this branch adds a file rather than rewriting a
 * shared one; `handlers.ts` spreads it in. Same rules as the file it joins:
 * contract-valid shapes and nothing else, money as integer paise, percentages
 * in basis points with integer floor division, and not a single float amount.
 *
 * THE TWO THINGS THIS FIXTURE EXISTS TO REPRODUCE.
 *
 * 1. A settlement that never closed. 15 of 166 on the 500-record runs, with a
 *    null tier, a null bank line and a null match — the rows a reviewer opens
 *    this listing to find, and the rows that had no way to reach the screen
 *    before it existed.
 *
 * 2. A T3 row whose columns do not add up. `net` is the bank credit and a T3
 *    match is precisely one where the reconstruction and the credit disagree
 *    within tolerance, so every T3 row here is 50 paise out and says so in its
 *    own evidence. A fixture where the arithmetic always closed would let a UI
 *    that silently balanced its columns look correct.
 */
import { http, HttpResponse } from "msw";
import { API_BASE } from "@/lib/api";
import type {
  PaginatedRecords,
  PaginatedSettlements,
  RecordSource,
  Settlement,
  SettlementTier,
} from "@/lib/explorer";
import type {
  BankLine,
  BatchNetting,
  MatchDetail,
  Metrics,
  Order,
  PSPTransaction,
  SubjectRecord,
} from "@/lib/types";
import { findRun } from "./fixtures";

/* ------------------------------------------------------------------ *
 * Deterministic primitives — the same ones `fixtures.ts` uses
 * ------------------------------------------------------------------ */

/** mulberry32 — tiny, fast, stable across reloads. */
function prng(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function hashString(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i += 1) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

/** `core/money.pct_of` — basis points, integer floor. Never a float. */
function pctOf(amountPaise: number, bps: number): number {
  return Math.floor((amountPaise * bps) / 10_000);
}

const MDR_BPS = 236;
const GST_BPS = 1800;

function pad(n: number, width: number): string {
  return String(n).padStart(width, "0");
}

function isoDate(dayOffset: number): string {
  const base = Date.UTC(2026, 7, 1); // 2026-08-01
  return new Date(base + dayOffset * 86_400_000).toISOString().slice(0, 10);
}

function isoDateTime(dayOffset: number, minuteOffset: number): string {
  const base = Date.UTC(2026, 7, 1, 9, 0, 0);
  return new Date(base + dayOffset * 86_400_000 + minuteOffset * 60_000)
    .toISOString()
    .slice(0, 19);
}

/* ------------------------------------------------------------------ *
 * The shape of one run's inputs and outputs
 * ------------------------------------------------------------------ */

/**
 * Row counts per source, in the proportions the committed 500-record fixture
 * actually has: 500 orders, 852 PSP legs, 171 bank lines. Everything is
 * generated by index rather than materialised, so a 50,000-record run costs
 * the same as a 50-record one and the listing is a real measurement of the
 * table rather than of a fixture build.
 */
type RunShape = {
  runId: string;
  orderCount: number;
  pspCount: number;
  bankCount: number;
  settlementCount: number;
  matchedCount: number;
  tierCounts: Metrics["tier_counts"] | null;
};

function shapeOf(runId: string): RunShape | null {
  const record = findRun(runId);
  if (!record) return null;

  const summary = record.summary;
  const tierCounts = summary.metrics?.tier_counts ?? null;
  // A run with no metrics has not reconstructed anything yet: it is still
  // executing, or it failed before it got there. Its records exist — they were
  // read — but its settlements do not.
  const settlementCount =
    tierCounts === null ? 0 : Math.floor(summary.record_count / 3);

  return {
    runId,
    orderCount: summary.record_count,
    pspCount: Math.round(summary.record_count * 1.704),
    bankCount: Math.round(summary.record_count * 0.342),
    settlementCount,
    matchedCount:
      tierCounts === null
        ? 0
        : Math.min(summary.match_count, settlementCount),
    tierCounts,
  };
}

/* ------------------------------------------------------------------ *
 * Settlements
 * ------------------------------------------------------------------ */

const TIER_ORDER: readonly SettlementTier[] = ["T0", "T1", "T2", "T3", "LLM"];

/** A prime coprime with every settlement count here, so the matched and the
 *  unclosed batches interleave instead of sitting in two blocks. */
const STRIDE = 7919;

function tierFor(
  ordinal: number,
  tierCounts: Metrics["tier_counts"],
): SettlementTier {
  let seen = 0;
  for (const tier of TIER_ORDER) {
    seen += tierCounts[tier];
    if (ordinal < seen) return tier;
  }
  return "T0";
}

function settlementAt(shape: RunShape, index: number): Settlement {
  const settlementId = `setl_${pad(index, 6)}`;

  const rank = (index * STRIDE) % shape.settlementCount;
  const unmatchedCount = shape.settlementCount - shape.matchedCount;
  const matched = rank >= unmatchedCount;
  const tier =
    matched && shape.tierCounts !== null
      ? tierFor(rank - unmatchedCount, shape.tierCounts)
      : null;

  const rng = prng(hashString(`${shape.runId}:${settlementId}`));
  const legs = 1 + (hashString(`${settlementId}:legs`) % 5);

  let gross = 0;
  for (let leg = 0; leg < legs; leg += 1) {
    gross += 18_000 + Math.floor(rng() * 260_000);
  }

  // MDR is charged on this settlement's own payment legs only, and GST on the
  // MDR. Refunds and holds reduce the net and never the fee base — which is
  // why `fees` is not 2.36% of the line above it once a refund is in the batch.
  const fees = pctOf(gross, MDR_BPS);
  const tax = pctOf(fees, GST_BPS);
  const refunds = legs > 3 ? 89_000 + Math.floor(rng() * 40_000) : 0;
  const holds = legs > 4 ? 50_000 : 0;
  const reconstructed = gross - fees - tax - refunds - holds;

  // THE T3 CASE. `net` is the bank credit. At T3 the credit and the
  // reconstruction disagree, within the matcher's 100-paise tolerance, and the
  // engine matched them anyway. Every other row's credit is the reconstruction
  // exactly.
  const net = tier === "T3" ? reconstructed - 50 : reconstructed;

  return {
    settlement_id: settlementId,
    gross,
    fees,
    tax,
    refunds,
    holds,
    net,
    payment_leg_count: legs,
    matched,
    bank_line_id: matched
      ? `BL-${pad(index % Math.max(1, shape.bankCount), 6)}`
      : null,
    match_id: matched ? `mat_${shape.runId}_${pad(index, 6)}` : null,
    tier,
  };
}

/* ------------------------------------------------------------------ *
 * Records
 * ------------------------------------------------------------------ */

const ORDER_STATUSES: Order["status"][] = [
  "paid",
  "refunded",
  "partially_refunded",
  "cancelled",
];

function orderAt(shape: RunShape, index: number): Order {
  const rng = prng(hashString(`${shape.runId}:order:${index}`));
  return {
    order_id: `ORD-${pad(400000 + index, 6)}`,
    order_date: isoDate(index % 21),
    customer_ref: `CUST-${pad(1000 + (index % 720), 5)}`,
    gross_amount: 12_000 + Math.floor(rng() * 780_000),
    currency: "INR",
    status: ORDER_STATUSES[index % ORDER_STATUSES.length],
  };
}

/**
 * PSP legs, bucketed by type in the order their id prefixes sort.
 *
 * The contract says this listing is ordered by `txn_id`, and `txn_id` carries
 * the leg's type as its prefix — so the buckets have to be laid out in
 * lexicographic prefix order for index order and id order to be the same
 * thing. Getting this wrong would show the same row on two pages, which is the
 * one failure a paged listing must not have.
 */
const PSP_BUCKETS: readonly {
  prefix: string;
  type: PSPTransaction["txn_type"];
  share: number;
}[] = [
  { prefix: "adj", type: "adjustment", share: 0.02 },
  { prefix: "cb", type: "chargeback", share: 0.03 },
  { prefix: "fee", type: "fee", share: 0.19 },
  { prefix: "pay", type: "payment", share: 0.5 },
  { prefix: "rfnd", type: "refund", share: 0.06 },
  { prefix: "rsv", type: "reserve", share: 0.01 },
  { prefix: "tax", type: "tax", share: 0.19 },
];

function pspBucketSizes(total: number): number[] {
  const sizes = PSP_BUCKETS.map((bucket) => Math.floor(total * bucket.share));
  const remainder = total - sizes.reduce((sum, n) => sum + n, 0);
  // Whatever the floors dropped goes to the payment legs, which are the ones a
  // settlement is measured in.
  sizes[3] += remainder;
  return sizes;
}

function pspAt(shape: RunShape, index: number): PSPTransaction {
  const sizes = pspBucketSizes(shape.pspCount);
  let bucket = 0;
  let ordinal = index;
  while (bucket < sizes.length - 1 && ordinal >= sizes[bucket]) {
    ordinal -= sizes[bucket];
    bucket += 1;
  }

  const { prefix, type } = PSP_BUCKETS[bucket];
  const rng = prng(hashString(`${shape.runId}:${prefix}:${ordinal}`));
  const magnitude = 5_000 + Math.floor(rng() * 900_000);
  // SIGNED from the merchant's point of view: payments and adjustments
  // positive, every deduction negative. Not a bank line's unsigned magnitude.
  const signed =
    type === "payment" || type === "adjustment" ? magnitude : -magnitude;

  // Fee and tax legs never carry an order reference by design; one payment leg
  // in three is the missing-order-reference defect.
  const carriesOrder =
    type !== "fee" && type !== "tax" && ordinal % 3 !== 0;
  // One leg in eleven belongs to no settlement batch at all — the orphan.
  const orphan = ordinal % 11 === 0;
  const settlementIndex = shape.settlementCount
    ? (ordinal * 7) % shape.settlementCount
    : 0;

  return {
    txn_id: `${prefix}_${pad(ordinal, 6)}`,
    txn_type: type,
    order_id: carriesOrder
      ? `ORD-${pad(400000 + (ordinal % Math.max(1, shape.orderCount)), 6)}`
      : null,
    captured_at: isoDateTime(1 + (ordinal % 21), ordinal % 480),
    amount: signed,
    settlement_id:
      orphan || shape.settlementCount === 0
        ? null
        : `setl_${pad(settlementIndex, 6)}`,
    settled_at: orphan ? null : isoDate(3 + (ordinal % 21)),
  };
}

const ENTITIES = ["ACME RET", "NORTHWIND", "GLOBEX", "UMBRELLA", "SOYLENT"];

/** Deliberately messy. Double spaces are data, not a formatting accident. */
function narrationFor(
  rng: () => number,
  index: number,
  settlementId: string,
): string {
  const entity = ENTITIES[index % ENTITIES.length];
  switch (index % 5) {
    case 0:
      return `NEFT RAZORPAY ${settlementId} CREDIT`;
    case 1:
      return `RZPX*${entity}  RET PL`;
    case 2:
      return `NEFT UTR: SBIN${pad(226534120000 + index, 12)} RAZORPAY`;
    case 3:
      return "MISC CREDIT 00000";
    default:
      return `RZPX*${entity}   PL  ${pad(Math.floor(rng() * 999999), 6)}`;
  }
}

function bankLineAt(shape: RunShape, index: number): BankLine {
  const rng = prng(hashString(`${shape.runId}:bank:${index}`));
  const settlementId = `setl_${pad(
    shape.settlementCount ? index % shape.settlementCount : index,
    6,
  )}`;
  const isDebit = index % 17 === 0;
  const magnitude = 100_000 + Math.floor(rng() * 9_000_000);

  return {
    line_id: `BL-${pad(index, 6)}`,
    txn_date: isoDate(2 + (index % 21)),
    // A debit line gets its own narration rather than one of the credit
    // shapes: a row posted as a debit whose narration says CREDIT is
    // incoherent data, and incoherent fixtures make a correct UI look wrong.
    narration: isDebit
      ? `RZPX*${ENTITIES[index % ENTITIES.length]}  RTN DR ${pad(index, 6)}`
      : narrationFor(rng, index, settlementId),
    // Direction is carried by which of the two is populated; both are
    // unsigned magnitudes.
    credit: isDebit ? null : magnitude,
    debit: isDebit ? magnitude : null,
    balance: 40_000_000 + Math.floor(rng() * 60_000_000),
    utr: index % 4 === 0 ? `SBIN${pad(226534120000 + index, 12)}` : null,
  };
}

function recordTotal(shape: RunShape, source: RecordSource): number {
  switch (source) {
    case "order":
      return shape.orderCount;
    case "psp_txn":
      return shape.pspCount;
    case "bank_line":
      return shape.bankCount;
  }
}

function recordAt(
  shape: RunShape,
  source: RecordSource,
  index: number,
): SubjectRecord {
  switch (source) {
    case "order":
      return orderAt(shape, index);
    case "psp_txn":
      return pspAt(shape, index);
    case "bank_line":
      return bankLineAt(shape, index);
  }
}

/* ------------------------------------------------------------------ *
 * Paging
 * ------------------------------------------------------------------ */

function pageBounds(url: URL, total: number) {
  const page = Math.max(1, Number(url.searchParams.get("page") ?? 1) || 1);
  const size = Math.max(1, Number(url.searchParams.get("size") ?? 50) || 50);
  const start = Math.min((page - 1) * size, total);
  const end = Math.min(start + size, total);
  return { page, size, start, end };
}

/* ------------------------------------------------------------------ *
 * The match a settlement breakdown opens
 * ------------------------------------------------------------------ */

/** `mat_<run_id>_<index>`, the same convention exception ids already use. */
const MATCH_ID = /^mat_(.+)_(\d{6})$/;

/**
 * The per-leg grosses of one settlement, replayed from the same seed and in
 * the same draw order `settlementAt` uses.
 *
 * They therefore sum to that settlement's `gross` exactly. This is the one
 * thing the netting diagram needs that the settlements listing does not carry,
 * and deriving it any other way would put a fan of orders on screen that does
 * not add up to the total beside it.
 */
function legGrossesOf(
  runId: string,
  settlementId: string,
  legs: number,
): number[] {
  const rng = prng(hashString(`${runId}:${settlementId}`));
  const out: number[] = [];
  for (let leg = 0; leg < legs; leg += 1) {
    out.push(18_000 + Math.floor(rng() * 260_000));
  }
  return out;
}

/**
 * The engine's account of why it closed a batch, in one place.
 *
 * Both `GET /api/matches/{id}` and `GET /api/runs/{id}/batches/{id}` carry
 * evidence for the same settlement, and a reader can now see both at once —
 * the breakdown panel and the diagram sit one above the other. Two copies of
 * this text would drift, and a drift would read as the engine contradicting
 * itself rather than as a fixture bug.
 */
function evidenceFor(settlement: Settlement, reconstructed: number): string[] {
  const residual = settlement.net - reconstructed;
  return [
    `${settlement.payment_leg_count} payment ${
      settlement.payment_leg_count === 1 ? "leg reconstructs" : "legs reconstruct"
    } to ${reconstructed} paise.`,
    `MDR ${MDR_BPS} bps on the payment-leg gross only; GST ${GST_BPS} bps on the MDR.`,
    residual === 0
      ? `Bank credit ${settlement.net} paise equals the reconstruction to the paise; single candidate in the ±1 day window.`
      : // The residual, in the engine's own words. This is the line a reviewer
        // is meant to find when the columns in the UI do not close.
        `Bank credit ${settlement.net} paise is ${Math.abs(residual)} paise ${
          residual < 0 ? "below" : "above"
        } the reconstructed ${reconstructed} paise — inside the 100 paise tolerance, so tier T3 accepts it. The residual is carried, not absorbed.`,
  ];
}

function matchDetailFor(matchId: string): MatchDetail | null {
  const parsed = MATCH_ID.exec(matchId);
  if (!parsed) return null;

  const [, runId, indexStr] = parsed;
  const shape = shapeOf(runId);
  if (!shape || shape.settlementCount === 0) return null;

  const index = Number(indexStr);
  if (index >= shape.settlementCount) return null;

  const settlement = settlementAt(shape, index);
  if (!settlement.matched || settlement.bank_line_id === null) return null;

  const reconstructed =
    settlement.gross -
    settlement.fees -
    settlement.tax -
    settlement.refunds -
    settlement.holds;

  const rng = prng(hashString(`${matchId}:subject`));
  const subject: BankLine = {
    line_id: settlement.bank_line_id,
    txn_date: isoDate(3 + (index % 21)),
    narration: `NEFT RAZORPAY ${settlement.settlement_id} CREDIT`,
    credit: settlement.net,
    debit: null,
    balance: 40_000_000 + Math.floor(rng() * 60_000_000),
    utr: `SBIN${pad(226534120000 + index, 12)}`,
  };

  const evidence = evidenceFor(settlement, reconstructed);

  return {
    match_id: matchId,
    bank_line_id: settlement.bank_line_id,
    settlement_id: settlement.settlement_id,
    psp_txn_ids: Array.from(
      { length: settlement.payment_leg_count },
      (_, leg) => `pay_${pad((index * 7 + leg) % 999_999, 6)}`,
    ),
    order_ids: Array.from(
      { length: settlement.payment_leg_count },
      (_, leg) => `ORD-${pad(400000 + ((index * 5 + leg) % 90_000), 6)}`,
    ),
    gross: settlement.gross,
    fees: settlement.fees,
    tax: settlement.tax,
    refunds: settlement.refunds,
    holds: settlement.holds,
    net: settlement.net,
    tier: settlement.tier ?? "T0",
    confidence: settlement.tier === "T0" ? 1 : 0.99,
    evidence,
    subject,
    audit_trail: [
      {
        entry_id: `aud_${matchId}_000`,
        run_id: runId,
        subject_id: subject.line_id,
        stage: "match",
        actor: "deterministic",
        rule: `${settlement.tier ?? "T0"}.batch_reconstruction`,
        evidence: evidence[0],
        confidence: 1,
        sequence: 0,
      },
      {
        entry_id: `aud_${matchId}_001`,
        run_id: runId,
        subject_id: subject.line_id,
        stage: "match",
        actor: "deterministic",
        rule: `${settlement.tier ?? "T0"}.accept`,
        evidence: evidence[2],
        confidence: 1,
        sequence: 1,
      },
    ],
  };
}

/* ------------------------------------------------------------------ *
 * The netting the settlement breakdown draws
 * ------------------------------------------------------------------ */

/** The ids the settlements listing hands out. Anything else is not ours. */
const SETTLEMENT_ID = /^setl_(\d{6})$/;

/**
 * `GET /api/runs/{id}/batches/{settlement_id}`, derived from the SAME
 * settlement the listing served.
 *
 * WHY THIS EXISTS AT ALL. `fixtures.ts` already answers this route, but it
 * fabricates a batch from a hash of whatever id it is handed — so asking it
 * for `setl_000001` returned 34 orders, ₹51,447.28 gross and bank line
 * BL-585646, against the 5 legs, ₹6,334.98 and BL-000001 the settlements
 * listing reports for that same id. Two fixture families, one id space, and
 * nothing ever showed both at once, so nothing ever caught it. Now that
 * opening a row draws that row, the two are stacked on one screen and the
 * disagreement is the first thing a reader sees. A real backend reads both
 * from the same run; this makes the mock do the same.
 *
 * Ids outside `setl_NNNNNN` are not answered here — the resolver returns
 * nothing and MSW passes the request to the fixture handler that already
 * serves the hand-picked `setl_C3` family.
 *
 * A batch that never closed is a 404, which is what the contract says: this
 * operation's response requires a bank line and a tier, so it cannot describe
 * an unclosed batch, and the UI must not be able to coax one out of it.
 */
function batchNettingFor(
  runId: string,
  settlementId: string,
): BatchNetting | null | "unclosed" {
  const parsed = SETTLEMENT_ID.exec(settlementId);
  if (!parsed) return null;

  const shape = shapeOf(runId);
  if (!shape || shape.settlementCount === 0) return null;

  const index = Number(parsed[1]);
  if (index >= shape.settlementCount) return null;

  const settlement = settlementAt(shape, index);
  if (
    !settlement.matched ||
    settlement.bank_line_id === null ||
    settlement.tier === null
  ) {
    return "unclosed";
  }

  const legs = legGrossesOf(runId, settlementId, settlement.payment_leg_count);
  const reconstructed =
    settlement.gross -
    settlement.fees -
    settlement.tax -
    settlement.refunds -
    settlement.holds;

  const psp_txn_ids = legs.map(
    (_, leg) => `pay_${pad((index * 7 + leg) % 999_999, 6)}`,
  );
  psp_txn_ids.push(`fee_${pad(index, 6)}`, `tax_${pad(index, 6)}`);
  if (settlement.refunds > 0) psp_txn_ids.push(`rfnd_${pad(index, 6)}`);
  if (settlement.holds > 0) psp_txn_ids.push(`cb_${pad(index, 6)}`);

  return {
    settlement_id: settlement.settlement_id,
    bank_line_id: settlement.bank_line_id,
    // Same order ids the match reports, in the same order, so the fan the
    // diagram draws and the list the match carries are one set of orders.
    orders: legs.map((gross_amount, leg) => ({
      order_id: `ORD-${pad(400000 + ((index * 5 + leg) % 90_000), 6)}`,
      gross_amount,
    })),
    psp_txn_ids,
    gross: settlement.gross,
    fees: settlement.fees,
    tax: settlement.tax,
    refunds: settlement.refunds,
    holds: settlement.holds,
    // `net` is the bank credit, not the reconstruction. On a T3 row the two
    // differ by 50 paise and the diagram draws the gap as its own segment.
    net: settlement.net,
    tier: settlement.tier,
    evidence: evidenceFor(settlement, reconstructed),
  };
}

/* ------------------------------------------------------------------ *
 * Handlers
 * ------------------------------------------------------------------ */

const url = (path: string) => `${API_BASE}${path}`;

const notFound = (detail: string) =>
  HttpResponse.json({ detail }, { status: 404 });

export const explorerHandlers = [
  /* GET /api/runs/{id}/settlements */
  http.get(url("/api/runs/:id/settlements"), ({ params, request }) => {
    const shape = shapeOf(String(params.id));
    if (!shape) return notFound(`No run ${params.id}`);

    const total = shape.settlementCount;
    const { page, size, start, end } = pageBounds(new URL(request.url), total);
    const items: Settlement[] = [];
    for (let i = start; i < end; i += 1) items.push(settlementAt(shape, i));

    return HttpResponse.json<PaginatedSettlements>({
      items,
      total,
      page,
      size,
    });
  }),

  /* GET /api/runs/{id}/records — `source` is required and refusing without it
     is the point: an empty page reads as "this run has no orders". */
  http.get(url("/api/runs/:id/records"), ({ params, request }) => {
    const requestUrl = new URL(request.url);
    const source = requestUrl.searchParams.get("source");

    if (
      source === null ||
      !["order", "psp_txn", "bank_line"].includes(source)
    ) {
      return HttpResponse.json(
        {
          detail:
            source === null
              ? "Query parameter 'source' is required. Legal values: order, psp_txn, bank_line."
              : `Query parameter 'source' must be one of order, psp_txn, bank_line — got '${source}'.`,
        },
        { status: 422 },
      );
    }

    const shape = shapeOf(String(params.id));
    if (!shape) return notFound(`No run ${params.id}`);

    const typed = source as RecordSource;
    const total = recordTotal(shape, typed);
    const { page, size, start, end } = pageBounds(requestUrl, total);
    const items: SubjectRecord[] = [];
    for (let i = start; i < end; i += 1) items.push(recordAt(shape, typed, i));

    return HttpResponse.json<PaginatedRecords>({
      items,
      total,
      page,
      size,
      source: typed,
    });
  }),

  /* GET /api/matches/{id} — only for the ids the settlements listing hands
     out. Anything else falls through to the handler that already exists:
     returning nothing from an MSW resolver passes the request on. */
  http.get(url("/api/matches/:id"), ({ params }) => {
    const detail = matchDetailFor(String(params.id));
    if (!detail) return undefined;
    return HttpResponse.json(detail);
  }),

  /* GET /api/runs/{id}/batches/{settlement_id} — the netting of a settlement
     this listing handed out, from that same settlement. Ids outside its own
     `setl_NNNNNN` space fall through to the fixture handler. */
  http.get(url("/api/runs/:id/batches/:settlementId"), ({ params }) => {
    const netting = batchNettingFor(
      String(params.id),
      String(params.settlementId),
    );
    if (netting === null) return undefined;
    if (netting === "unclosed") {
      return notFound(
        `Settlement ${params.settlementId} closed against no bank line, so it has no netting breakdown.`,
      );
    }
    return HttpResponse.json(netting);
  }),
];
